# Generated by Django 4.2.16 on 2024-11-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, upload_to='myblog/%Y/%m/%d'),
        ),
    ]
