# Generated by Django 4.2.16 on 2024-11-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='creataed_at',
            new_name='created_at',
        ),
    ]
